name: Sync Maven Repository

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0:00 同步
  workflow_dispatch:

jobs:
  download_files:
    runs-on: ubuntu-latest

    steps:
      - name: Upgrade OS
        run: sudo apt update -y && sudo apt full-upgrade -y

      - name: Install Golang
        run: sudo apt install golang -y

      - name: Verify Golang version
        run: go version
