name: Get Maven Repository Metadata

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0:00 同步
  workflow_dispatch:

jobs:
  get_maven_repository_metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Upgrade os
        run: sudo apt update -y && sudo apt full-upgrade -y

      - name: Install wget
        run: sudo apt install wget -y

      - name: Set timezone
        run: sudo timedatectl set-timezone Asia/Shanghai

      - name: Get all 'maven-metadata.xml' files from https://repo1.maven.org/maven2/
        run: wget -r -np -L -e robots=off --no-check-certificate -A "maven-metadata.xml" --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3" https://repo1.maven.org/maven2/ | grep ' saved '

      - name: Find all 'maven-metadata.xml' files and save filepaths to maven-metadata-files.txt
        run: find ./ -name 'maven-metadata.xml' > ./maven-metadata-files.txt

#      - name: Install golang
#        run: sudo apt install golang -y
#
#      - name: Verify golang version
#        run: go version
#
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Build executable program
#        run: go mod tidy && go build -o ./main .
#
#      - name: Add executable permission
#        run: sudo chmod +x main
#
#      - name: Run
#        run: ./main
