name: Get Maven Repository Metadata

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0:00 同步
  workflow_dispatch:

jobs:
  get_maven_repository_metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Upgrade os
        run: sudo apt update -y && sudo apt full-upgrade -y

      - name: Install golang
        run: sudo apt install golang -y

      - name: Verify golang version
        run: go version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build executable program
        run: go build -o ./main .

      - name: Add executable permission
        run: sudo chmod +x main

      - name: Run
        run: ./main
