name: Sync Maven Repository

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0:00 同步
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync Maven Repository
        run: |
          rsync -aHAXxv --exclude="*.jar" --delete-after --progress rsync://repo1.maven.org/maven2/ ./maven2/
          git add -A
          git commit -m "Sync Maven Repository"
          git push
